### ISSUE TITLE
Post-Deliverable Checklist Sprint 1

### ISSUE THREAD

**Issue by mikeybacque** [robcodonnell/simple-chat-app#7]

**Comment by mikeybacque** [comment]
# Progress
- [x] Paper Wireframes
  - [] 404 page
  - [x] Chat (main) page
  - [] Members List
  - [x] Notifications
    - [x] Joined
    - [x] Left

# Issues
Completed: #5 

# Positives :+1:

+ we completed the deliverables on time
+ had a great time working together

# Improvements :star:

+ better focus on content
+ team communication

# Request for Feedback :ear:

+ how was our presentation of the paper prototypes compared to industry standard?

**Comment by robcodonnell** [comment]
# Progress
- [ ] Paper Wireframes
  - [ ] 404 page
  - [x] Chat (main) page
  - [x] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left

# Issues
Completed: #4 

# Positives :+1:

+ Got inspired to work ahead 
+ Had a fun time with the wireframes

# Improvements :star:

+ Group roles need to be better defined

# Request for Feedback :ear:

+ how was our presentation of the paper prototypes compared to industry standard?

**Comment by erinmilling** [comment]
# Progress
- [ ] Paper Wireframes
  - [x] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left
-  [x] Researched other chat apps

# Issues
Completed #2

# Positives :+1:
+ Learned a lot about chat apps
+ Came up with a solid chat app name (to be announced)

# Improvements :star:
+ Sharing of ideas throughout the week prior to deadline.

# Request for Feedback :ear:
+ If our ideas are too far fetched? Having read receipts for example.

**Comment by ericadamski** [comment]
Awesome feedback questions guys! We can talk more about it in class
